# Generated by Django 2.1 on 2018-09-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_status', models.BooleanField(default=False)),
                ('time_interval', models.IntegerField(default=0)),
                ('max_lost', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
