# Generated by Django 2.1 on 2018-09-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='db_verbosity',
            field=models.CharField(default='medium', max_length=100),
            preserve_default=False,
        ),
    ]
