# Generated by Django 2.1 on 2018-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_botconfig_db_verbosity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='botconfig',
            name='currencies',
            field=models.ManyToManyField(related_name='configs', to='configuration.Currency'),
        ),
    ]
