# Generated by Django 2.1 on 2018-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20180921_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='db_verbosity',
            field=models.CharField(choices=[('silent', 'Silent'), ('medium', 'Medium')], max_length=100),
        ),
    ]
