# Generated by Django 2.1 on 2018-10-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_symbol',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
