# Generated by Django 2.1 on 2018-08-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parity', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('commission', models.DecimalField(decimal_places=10, max_digits=19)),
                ('okex_order', models.IntegerField(default=0)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transactions.Transaction')),
            ],
        ),
    ]
