# Generated by Django 2.1 on 2018-09-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180905_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_order',
            field=models.IntegerField(default=0),
        ),
    ]
