# Generated by Django 2.1 on 2018-10-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactiondetail_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='action',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=6),
            preserve_default=False,
        ),
    ]
