# Generated by Django 2.1 on 2018-10-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactiondetail_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='parity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='configuration.Currency'),
        ),
    ]
